import Head from "next/head";
import Chessboard from "../components/Chessboard";
import { ChessboardProvider } from "../context/ChessboardContext";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chess Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ChessboardProvider>
        <Chessboard />
      </ChessboardProvider>
    </div>
  );
}
