import Head from "next/head";
import Chessboard from "../components/Chessboard";
import { ChessboardProvider } from "../context/chessboard/ChessboardContext";
import styles from "../styles/Home.module.css";
import io from "socket.io-client";
import { useEffect, useState } from "react";
import Options from "../components/Options";
import Chat from "../components/Chat";
import { SocketProvider } from "../context/socket/SocketContext";

export default function Home() {
  const [socket, setSocket] = useState(null);

  useEffect(() => {
    socketInitializer();
  }, []);

  const socketInitializer = async () => {
    await fetch("api/socket");
    const socket = io();

    socket.on("connect", () => {
      console.log("Connected to server");
      setSocket(socket);
    });

    socket.on("disconnect", () => {
      console.log("Disconnected from server");
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Chess Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SocketProvider socket={socket}>
        <ChessboardProvider>
          <Options />
          <Chessboard />
          <Chat />
        </ChessboardProvider>
      </SocketProvider>
    </div>
  );
}
